export enum SelectItemTypeEnum {
    LOCATION,
    ARTICLE_TO_PICK,
    DEMANDE_LIVRAISON_TYPE,
    DEMANDE_LIVRAISON_ARTICLES,
    INVENTORY_LOCATION,
    INVENTORY_ARTICLE,
    INVENTORY_ANOMALIES_LOCATION,
    INVENTORY_ANOMALIES_ARTICLE
}
