package io.ionic.starter.plugins.rfid.manager.exceptions;

public enum ZebraExceptionType {
    ACTION_INVALID,
    ACTION_REQUIRED,
    READER_ALREADY_CONNECTED,
    READER_CONNECTION_FAILURE,
    NO_READER_FOUND,
    READER_ALREADY_DISCONNECTED,
    READER_DISCONNECTION_FAILURE,
    READER_CONFIGURATION_FAILED,
    READER_NOT_CONNECTED,
    SCAN_STOP_FAILED,
    SCAN_START_FAILED,
}
