export type IconColor = 'primary'
                      | 'success'
                      | 'secondary'
                      | 'danger'
                      | 'light'
                      | 'dark'
                      | 'grey'
                      | 'green'
                      | 'white'
                      | 'list-blue'
                      | 'list-blue-light'
                      | 'list-orange'
                      | 'list-orange-light'
                      | 'list-yellow'
                      | 'list-yellow-light';
